#!/bin/sh

VIMDIR=.vim
REMOTE_HOST=""
REMOTE_USER=${USER}
REMOTE_DIR=""
REMOTE=0
GET=0

usage () {
   echo "Args:"
   echo "-r: remote install"
   echo "-g: get setup (set otherwise)"
   echo "-d: remote dir"
   echo "-u: remote user"
   echo "-h: remote host"
   exit 1
}

while getopts "Hrgd:u:h:" o; do
   case "${o}" in
      r) REMOTE=1
         ;;
      g) GET=1
         ;;
      d) REMOTE_DIR="${OPTARG}"
         ;;
      u) REMOTE_USER="${OPTARG}"
         ;;
      h) REMOTE_HOST="${OPTARG}"
         ;;
      H) usage
         ;;
      *) usage
         ;;
         
    esac
 done
shift $((OPTIND-1))

if [ "${GET}" -eq 1 ]; then
   if [ ${REMOTE} -eq 1 ]; then
      echo "Getting setup from ${REMOTE_USER}@${REMOTE_HOST}:"
      rsync -avzh ${REMOTE_USER}@${REMOTE_HOST}:${VIMDIR} .
   else
      echo "Getting local setup"
      cp -a ~/${VIMDIR} .
   fi
else
   if [ ${REMOTE} -eq 1 ]; then
      echo "Setting setup to ${REMOTE_USER}@${REMOTE_HOST}:"
      rsync -avzh ${VIMDIR} ${REMOTE_USER}@${REMOTE_HOST}:
   else
      echo "Setting local setup"
      rm -fr ${HOME}/${VIMDIR}
      cp -a ${VIMDIR} ${HOME}/
   fi
fi
